services:
  mysqldb:
    image: mysql:5.6
    container_name: mysqldb
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db
    # volumes:
    #   - ./mysql-data:/var/lib/mysql
    ports:
      - 3333:3306